### ISSUE TITLE
Add a fast version of fannkuchredux to the benchmark suite

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#370]
The fast version is here: https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/fannkuchredux-ocaml-3.html

You may consider removing the slow versions `fannkuchredux` and `fannkuchredux2`.

**Comment by moazzammoriani** [comment]
I have a [working version ](https://github.com/moazzammoriani/fannkuchredux/blob/main/fannkuchredux.ml l) of this benchmark that uses domainslib instead of the unix library. However, this benchmark cannot be run without compiling it with the `noassert` and `unsafe` flags. Since my benchmark is adapted from the one you have linked, it too cannot work without these two flags. @Sudha247 and I were discussing whether including this particular benchmark with these flags might introduce a bias in the results since the other benchmarks don't use these flags. Maybe you and @shakthimaan have some thoughts on this?
